export const environment = {
  production: false,
  firebase: {
    apiKey: "xxxx",
    authDomain: "xxxx",
    projectId: "xxxx",
    messagingSenderId: "xxxx",
    appId: "xxxx"
  },

  getAdminLoginDetailsApiURL: 'https://ruralx.in/api/getAdminLoginDetails.php',
  searchApiUrl: 'https://ruralx.in/api/search_product.php',
  uploadDataApiUrl: 'https://ruralx.in/api/uploadAdminData.php',
  insertAdminLoginDetailsApiUrl: 'https://ruralx.in/api/insertAdminLoginDetails.php',
  getProductListDetailsApiUrl: 'https://ruralx.in/api/getAdminProductList.php',
  getProductNotifyApiUrl: 'https://ruralx.in/api/getProductNotification.php',
  deleteProductListDetailsApiUrl: 'https://ruralx.in/api/delete_product.php',
  deleteCustomerListDetailsApiUrl: 'https://ruralx.in/api/delete_customer.php',
  deleteOrderListDetailsApiUrl: 'https://ruralx.in/api/delete_order.php',
  updateUserDetailsApiUrl:'https://ruralx.in/api/updateUserDetails.php',
  updateProductDetailsApiUrl:'https://ruralx.in/api/updateProductDetails.php',
  updateCategoryDetailsApiUrl:'https://ruralx.in/api/updateCategoryDetails.php',
  editOrderDetailsApiUrl:'https://ruralx.in/api/editOrderDetails.php',
  insertStoreDetailsApiUrl:'https://ruralx.in/api/insertstoreList.php',
  getStoreDetailsApiUrl:'https://ruralx.in/api/getStoreList.php',
  deleteStoreDetailsApiUrl:'https://ruralx.in/api/deleteStore.php',
  getOrderListApiUrl: 'https://ruralx.in/api/getOrders.php',
  getPendingOrderApiUrl: 'https://ruralx.in/api/pending_order.php',
  getOrderByIdApiUrl: 'https://ruralx.in/api/get_order_by_id.php',
  upadateStatusApiUrl: 'https://ruralx.in/api/update_order_status.php',
  getOrderListByStatusApiUrl: 'https://ruralx.in/api/getOrderListByStatus.php',
  getEmployeeDetailsApiUrl: 'https://ruralx.in/employee-get.php',
  saveEmployeeDetailsApiUrl: 'https://ruralx.in/employee-save.php',
  updateEmployeeDetailsApiUrl: 'https://ruralx.in/employee-update.php',
  deleteEmployeeDetailsApiUrl: 'https://ruralx.in/employee-delete.php',
  getSalarySlipApiUrl: 'https://ruralx.in/get_salary_months.php',
  sendOtpApiUrl:'https://ruralx.in/api/send-otp.php',
  verifyOtpApiUrl:'https://ruralx.in/api/verify-otp.php',
  getAllReviewApiUrl: 'https://ruralx.in/api/get-admin-review.php',
  getApproveReviewApiUrl: 'https://ruralx.in/api/approve-review.php',
  getRejectedReviewApiUrl: 'https://ruralx.in/api/reject-review.php',
  getadminDashboardApiUrl: 'https://ruralx.in/api/admin-dashboard.php',
  getReturnOrdersApiUrl: 'https://ruralx.in/api/get-return-order.php',
  getUpdateReturnStatusApiUrl: 'https://ruralx.in/api/update-return-status.php',
  getAssignReturnDeliveryApiUrl: 'https://ruralx.in/api/assign-return-delivery.php',
  getPickupCompleteApiUrl:'https://ruralx.in/api/pickup-complete.php',
  getCompleteRefundApiUrl:'https://ruralx.in/api/complete-refund.php',
  getShipReplacementApiUrl:'https://ruralx.in/api/shipReplacement.php',
  getCompleteReplacementApiUrl:'https://ruralx.in/api/completeReplacement.php',

  


  // getUserDetailsApiURL: 'https://ruralx.in/getUserLoginDetails.php',
  // searchApiUrl: 'https://ruralx.in/search_product.php',
   //uploadDataApiUrl: 'https://ruralx.in/uploadAdminData.php',
  // insertUserDetailsApiUrl: 'https://ruralx.in/insertUserDetailsData.php',
  // getProductListDetailsApiUrl: 'https://ruralx.in/getProductDetails.php',
  // productBuyerApiUrl: 'https://ruralx.in/productbuyer.php',
  // getProductNotifyApiUrl: 'https://ruralx.in/getProductNotification.php',
  // getBuyerDataApiUrl: 'https://ruralx.in/getProductBuyerData.php',
  // deleteProductListDetailsApiUrl: 'https://ruralx.in/delete_product.php',
  // deleteCustomerListDetailsApiUrl: 'https://ruralx.in/delete_customer.php',
  // deleteOrderListDetailsApiUrl: 'https://ruralx.in/delete_order.php',
  // updateUserDetailsApiUrl: 'https://ruralx.in/updateUserDetails.php',
  // updateProductDetailsApiUrl: 'https://ruralx.in/updateProductDetails.php',
  // updateCategoryDetailsApiUrl: 'https://ruralx.in/updateCategoryDetails.php',
  // editOrderDetailsApiUrl: 'https://ruralx.in/editOrderDetails.php',
  // insertStoreDetailsApiUrl: 'https://ruralx.in/insertstoreList.php',
  // getStoreDetailsApiUrl: 'https://ruralx.in/getStoreList.php',
  // deleteStoreDetailsApiUrl: 'https://ruralx.in/deleteStore.php',
  // getOrderListApiUrl: 'https://ruralx.in/api/getOrders.php',
  // getPendingOrderApiUrl: 'https://ruralx.in/pending_order.php',
  // getOrderByIdApiUrl: 'https://ruralx.in/get_order_by_id.php',
  // upadateStatusApiUrl: 'https://ruralx.in/update_order_status.php',

};

